apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "harbor-container-webhook.fullname" . }}
  labels:
    {{- include "harbor-container-webhook.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "harbor-container-webhook.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
        checksum/configmap: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
        {{- if .Values.harbor.credentials.pass }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
      labels:
        {{- include "harbor-container-webhook.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "harbor-container-webhook.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          args:
            - --config=/etc/hcw/config/webhook-config.yaml
            {{- range $arg := .Values.extraArgs }}
            - {{ $arg }}
            {{- end }}
            {{- with .Values.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if .Values.harbor.credentials.pass }}
          envFrom:
            - secretRef:
                name: {{ include "harbor-container-webhook.fullname" . }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: https
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.healthPort }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.healthPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/hcw/config
              name: config
              readOnly: true
            {{- if .Values.certManager.enabled }}
            - mountPath: /etc/hcw/certs
              name: certs
              readOnly: true
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "harbor-container-webhook.fullname" . }}
        {{- if .Values.certManager.enabled }}
        - name: certs
          secret:
            secretName: {{ include "harbor-container-webhook.fullname" . }}-certs
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
