{{- if .Values.harbor.credentials.pass }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harbor-container-webhook.fullname" . }}
  labels:
    {{- include "harbor-container-webhook.labels" . | nindent 4 }}
data:
  HARBOR_USER: {{ .Values.harbor.credentials.user }}
  HARBOR_PASS: {{ .Values.harbor.credentials.pass }}
{{- end }}