apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "harbor-container-webhook.name" . }}
  {{- if .Values.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: "{{ .Release.Namespace }}/{{ include "harbor-container-webhook.name" . }}"
  {{- end }}
webhooks:
  - name: {{ include "harbor-container-webhook.name" . }}.{{ .Release.Namespace }}.svc
    sideEffects: None
    reinvocationPolicy: IfNeeded
    admissionReviewVersions:
      - v1beta1
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - "v1"
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
    failurePolicy: Ignore
    clientConfig:
      service:
        name: {{ include "harbor-container-webhook.name" . }}
        namespace: {{ .Release.Namespace }}
        path: "/webhook-v1-pod"
